### ISSUE TITLE
telocomp_Assembly error

### ISSUE THREAD

**Issue by Bobo22331** [lxie-0709/TeloComp#9]
Hi, 
When I run the telocomp_Assembly step, it occurs the following error:

```
[106279 ERROR] 2025-09-29 11:12:05 Failed to correct sequence: A07_shortest_ONT_L
Traceback (most recent call last):
  File "/home/cuixb/tools/biosoft/TeloComp-1.0.0/bin/telocomp_Assembly", line 196, in asm_contig_racon
    subprocess.run(c,shell=True,check=True)
  File "/home/cuixb/tools/biosoft/conda3/envs/py3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'python /home/cuixb/tools/biosoft/NextPolish//lib/nextpolish2.py -g asm_merged_All_chr.fasta -l tmp_dir/pb.map.bam.fofn -r clr -p 20 -o tmp_dir/merged_genome.lgspolish.fasta' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/cuixb/tools/biosoft/TeloComp-1.0.0/bin/telocomp_Assembly", line 407, in <module>
    main()
  File "/home/cuixb/tools/biosoft/TeloComp-1.0.0/bin/telocomp_Assembly", line 400, in main
    process_asm_merge_fasta_files(
  File "/home/cuixb/tools/biosoft/TeloComp-1.0.0/bin/telocomp_Assembly", line 316, in process_asm_merge_fasta_files
    asm_contig_racon(output_file,lgsreads,wgs1,wgs2,threads,NextPolish)
  File "/home/cuixb/tools/biosoft/TeloComp-1.0.0/bin/telocomp_Assembly", line 199, in asm_contig_racon
    err=e.stderr.decode() if hasattr(e,'stderr') else str(e)
AttributeError: 'NoneType' object has no attribute 'decode'
```
The full log file of telocomp_Assembly: 

[telocomp_Assembly.log](https://github.com/user-attachments/files/22917602/telocomp_Assembly.log)

**Comment by zhangraytk** [comment]
Hi, hcsun1
See #4
The actual issue lies in nextpolish2.py. You need to provide the specific error messages rather than the TeloComp_Assembly log.
I recommend running the NextPolish test dataset first, as this error is most likely caused by an environment issue.

**Comment by lxie-0709** [comment]
We have fixed the issues encountered during the assembly process and updated the changes on GitHub. Thank you for your feedback and support!

**Comment by LN-11** [comment]
> We have fixed the issues encountered during the assembly process and updated the changes on GitHub. Thank you for your feedback and support!

Hi, I noticed that even after downloading the latest version from GitHub, I am still encountering assembly errors. Has the most recent version been uploaded to GitHub?
